backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "paintings"
    label: "Portfolio items"
    folder: "content/paintings"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Jaar", name: "year", widget: "number" }
      - { label: "Beschrijving", name: "body", widget: "markdown" }
      - { label: "Afbeelding", name: "image", widget: image }
      - { label: "Weergeven op de pagina", name: "show", widget: "boolean" }

  - name: "over-edze"
    label: "Over Edze"
    files:
      - file: "content/over-edze/image-big.md"
        label: "Grote afbeelding"
        name: "image-big"
        fields:
          - { label: "Grote afbeelding (Over Edze)", name: "image", widget: "image" }
      - file: "content/over-edze/p1.md"
        label: "Eerste alinea"
        name: "p1"
        fields:
          - { label: "Eerste alinea (Over Edze)", name: "body", widget: "markdown" }
      - file: "content/over-edze/images-small.md"
        label: "Drie kleine afbeeldingen"
        name: "images-small"
        fields:
          - { label: "Eerste kleine afbeelding (Over Edze)", name: "image1", widget: "image" }
          - { label: "Tweede kleine afbeelding (Over Edze)", name: "image2", widget: "image" }
          - { label: "Derde kleine afbeelding (Over Edze)", name: "image3", widget: "image" }
      - file: "content/over-edze/p2.md"
        label: "Tweede alinea"
        name: "p2"
        fields:
          - { label: "Tweede alinea (Over Edze)", name: "body", widget: "markdown" }

  - name: "footer"
    label: "Footer teksten"
    files:
      - file: "content/footer/footer.md"
        label: "Footer"
        name: "footer"
        fields:
          - { label: "Footer titel", name: "title", widget: "string" }
          - { label: "Footer tekst", name: "body", widget: "markdown" }
